### ISSUE TITLE
gatsby-transformer-rehype with custom plugin not working in Gatsby v3.14

### ISSUE THREAD

**Issue by Kerumen** [styxlab/gatsby-theme-try-ghost#292]
I have a custom plugin located in my `plugins` folder. It's named `gatsby-rehype-custom-toc`.

The relevant part of my `gatsby-config.js` looks like this:

```
{
  resolve: 'gatsby-transformer-rehype',
  options: {
    filter: (node) => node.internal.type === 'GhostPost',
    plugins: [
      { resolve: 'gatsby-rehype-ghost-links' },
      { resolve: 'gatsby-rehype-custom-toc' },
    ],
  },
},
```

In Gatsby v3.13 everything works fine but when I upgraded to v3.14 it breaks with this error:

```
"gatsby-transformer-rehype" threw an error while running the createSchemaCustomization lifecycle:

Cannot find module 'gatsby-rehype-custom-toc'
```

Maybe this is related to [this part](https://www.gatsbyjs.com/docs/reference/release-notes/v3.14/#preparations-for-gatsby-v4) of the changelog?
